
ENVIROMENT_DEBUG = "http://localhost:9090"
ENVIROMENT_DEBUG_JSON = "http://localhost:8000"
ENVIROMENT_DEBUG_PRODUCTION_JSON = "http://localhost:9090"
ENVIROMENT_PRODUCTION = "http://apinvoice.pythonanywhere.com"


#CHANGES CONSTANTS
ENVIROMENT = ENVIROMENT_DEBUG
ENVIROMENT_JSON = ENVIROMENT_DEBUG_JSON

# SETTINGS
TYPE_DOCUMENTI = ENVIROMENT+"/settings/Type_DocumentI/"
TYPE_ORGANIZATIONS = ENVIROMENT+"/settings/Type_Organizations/"
TYPE_REGIMEN = ENVIROMENT+"/settings/Type_Regimen/"
MUNICIPALITYS = ENVIROMENT+"/settings/Municipalitys/"

# EMPLOYEE
VALIDATE_LOGIN = ENVIROMENT+"/employee/Validate_Login/"
GET_LIST_EMPLOYEE = ENVIROMENT+"/employee/GET_LIST_EMPLOYEE/"
GET_EMPLOYEE = ENVIROMENT+"/employee/GET_EMPLOYEE/"
EDIT_EMPLOYEE = ENVIROMENT+"/employee/EDIT_EMPLOYEE/"
REGISTER_EMPLOYEE = ENVIROMENT+"/employee/Register_Employee/"

# CLIENT
GET_LIST_CLIENT = ENVIROMENT+"/client/GET_LIST_CLIENT/"
GET_CLIENT = ENVIROMENT+"/client/GET_CLIENT/"
DELETE_CLIENT = ENVIROMENT+"/client/DELETE_CLIENT/"
CREATE_CLIENT = ENVIROMENT+"/client/CREATE_CLIENT/"
EDIT_CLIENT = ENVIROMENT+"/client/EDIT_CLIENT/"

# INVOICE
CREATE_INVOICE = ENVIROMENT+"/invoice_fe/CREATE_INVOICE/"
GET_LIST_INVOICE = ENVIROMENT+"/invoice_fe/GET_LIST_INVOICE/"
SEND_DIAN = ENVIROMENT+"/invoice_fe/Send_DIAN/"
GET_CONSECUTIVE = ENVIROMENT+"/invoice_fe/GET_CONSECUTIVE/"
GET_INVOICE = ENVIROMENT+"/invoice_fe/GET_INVOICE/"

# INVENTORY
GET_LIST_INVENTORY = ENVIROMENT+"/inventory/GET_LIST_INVENTORY/"
GET_PRODUCT = ENVIROMENT+"/inventory/GET_PRODUCT/"
UPDATED_PRODUCT = ENVIROMENT+"/inventory/UPDATE_PRODUCT/"
DELETE_PRODUCT = ENVIROMENT+"/inventory/DELETE_PRODUCT/"
CREATE_INVENTORY = ENVIROMENT+"/inventory/CREATE_INVENTORY/"

# SHOPPING
CREATE_SHOPPINGS = ENVIROMENT +"/shopping/CREATE_SHOPPINGS/"
CHECK_INVOICE_NUMBER = ENVIROMENT +"/shopping/CHECK_INVOICE_NUMBER/"





# JSON
FILE_JSON_INVOICE_FE = "./static/data_fe.json"
FILE_JSON_INVOICE_POS = "./static/data_pos.json"
FILE_JSON_EARRING = "./static/earring.json"
FILE_JSON_CLIENTS = "./static/clients.json"
FILE_JSON_INVENTORY = "./static/inventory.json"
FILE_JSON_TYPE_DOCUMENTI = "./static/type_documentI.json"
LIST_EMPLOYEE = "./static/employee.json"
URL_PDF_PLATFORM = 'C:/laragon/www/apidian2021/storage/app/public/'